push dev:
  tags:
    - meao
  only: dev
  script:
    - bin/build.sh dev
    - bin/push-gh-pages.sh

push stage:
  tags:
    - meao
  only: master
  script:
    - bin/build.sh stage
    - "cd release && aws s3 sync . s3://awebpodcast-stage --acl public-read --delete --profile awebpodcast"

push prod:
  tags:
    - meao
  only: prod
  script:
    - bin/build.sh prod
    - "cd release && aws s3 sync . s3://awebpodcast --acl public-read --delete --profile awebpodcast"
